version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Madrid
    ports:
      - "1880:1880"
    networks:
      - node-red-demo
    volumes:
      - ./node-red-data:/data
  php:
    container_name: php
    build:
      context: .
      dockerfile: etc/infrastructure/php/Dockerfile
    ports:
      - '9000:9000'
    networks:
      - node-red-demo
    volumes:
      - ./sandbox/config:/var/www/sandbox/config
      - ./sandbox/public:/var/www/sandbox/public
      - ./sandbox/src:/var/www/sandbox/src
      - ./sandbox/composer.json:/var/www/sandbox/composer.json
      - ./sandbox/composer.lock:/var/www/sandbox/composer.lock
      - ./storage:/var/www/sandbox/storage
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    networks:
      - node-red-demo
    volumes:
      - ./sandbox/public:/var/www/sandbox/public
      - ./etc/infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
networks:
  node-red-demo:
